// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/food_log/data/local/food_entry_entity.dart';
import 'features/food_log/data/local/food_item_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 6520481191571220998),
    name: 'FoodEntryEntity',
    lastPropertyId: const obx_int.IdUid(4, 8813906759674206801),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 992164481216448084),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5246236759718317235),
        name: 'foodItemId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 1980821698951784091),
        relationField: 'foodItem',
        relationTarget: 'FoodItemEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 16328515590806273),
        name: 'dateTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8813906759674206801),
        name: 'quantity',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 512092194566140640),
    name: 'FoodItemEntity',
    lastPropertyId: const obx_int.IdUid(12, 1904513673239261049),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 223987612548900379),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6759781069428740544),
        name: 'barcode',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(4, 2099678179155011358),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1153490806350976988),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8688581141932851748),
        name: 'brand',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2307027584078546345),
        name: 'caloriesPer100g',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 469334674520105607),
        name: 'carbsPer100g',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6096255856162016400),
        name: 'proteinPer100g',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3392300653778563978),
        name: 'fatsPer100g',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7187199050961751529),
        name: 'fiberPer100g',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1124410462323489806),
        name: 'servingSizeWeight',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5862898075594288085),
        name: 'servingSizeName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 1904513673239261049),
        name: 'allergies',
        type: 30,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 512092194566140640),
    lastIndexId: const obx_int.IdUid(4, 2099678179155011358),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [831402211557804926, 4590642211799563445],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      1892218377980231136,
      9048116492312893075,
      9066962400477943637,
      8108737585855767412,
      976503164000436458,
      1329695433554647114,
      4262759751927146726,
      5909925021469807195,
      6635341138356018258,
      8444862756584125319,
      4604354847991903998,
      5065836201845449059,
      2864818224448073714,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    FoodEntryEntity: obx_int.EntityDefinition<FoodEntryEntity>(
      model: _entities[0],
      toOneRelations: (FoodEntryEntity object) => [object.foodItem],
      toManyRelations: (FoodEntryEntity object) => {},
      getId: (FoodEntryEntity object) => object.id,
      setId: (FoodEntryEntity object, int id) {
        object.id = id;
      },
      objectToFB: (FoodEntryEntity object, fb.Builder fbb) {
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.foodItem.targetId);
        fbb.addInt64(2, object.dateTime.millisecondsSinceEpoch);
        fbb.addFloat64(3, object.quantity);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = FoodEntryEntity()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..dateTime = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
          )
          ..quantity = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          );
        object.foodItem.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.foodItem.attach(store);
        return object;
      },
    ),
    FoodItemEntity: obx_int.EntityDefinition<FoodItemEntity>(
      model: _entities[1],
      toOneRelations: (FoodItemEntity object) => [],
      toManyRelations: (FoodItemEntity object) => {},
      getId: (FoodItemEntity object) => object.id,
      setId: (FoodItemEntity object, int id) {
        object.id = id;
      },
      objectToFB: (FoodItemEntity object, fb.Builder fbb) {
        final barcodeOffset = object.barcode == null
            ? null
            : fbb.writeString(object.barcode!);
        final nameOffset = fbb.writeString(object.name);
        final brandOffset = object.brand == null
            ? null
            : fbb.writeString(object.brand!);
        final servingSizeNameOffset = object.servingSizeName == null
            ? null
            : fbb.writeString(object.servingSizeName!);
        final allergiesOffset = object.allergies == null
            ? null
            : fbb.writeList(
                object.allergies!.map(fbb.writeString).toList(growable: false),
              );
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, barcodeOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, brandOffset);
        fbb.addFloat64(4, object.caloriesPer100g);
        fbb.addFloat64(5, object.carbsPer100g);
        fbb.addFloat64(6, object.proteinPer100g);
        fbb.addFloat64(7, object.fatsPer100g);
        fbb.addFloat64(8, object.fiberPer100g);
        fbb.addFloat64(9, object.servingSizeWeight);
        fbb.addOffset(10, servingSizeNameOffset);
        fbb.addOffset(11, allergiesOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = FoodItemEntity()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..barcode = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 6)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..brand = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 10)
          ..caloriesPer100g = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            12,
            0,
          )
          ..carbsPer100g = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            14,
            0,
          )
          ..proteinPer100g = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            16,
            0,
          )
          ..fatsPer100g = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            18,
            0,
          )
          ..fiberPer100g = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            20,
            0,
          )
          ..servingSizeWeight = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            22,
            0,
          )
          ..servingSizeName = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 24)
          ..allergies = const fb.ListReader<String>(
            fb.StringReader(asciiOptimization: true),
            lazy: false,
          ).vTableGetNullable(buffer, rootOffset, 26);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [FoodEntryEntity] entity fields to define ObjectBox queries.
class FoodEntryEntity_ {
  /// See [FoodEntryEntity.id].
  static final id = obx.QueryIntegerProperty<FoodEntryEntity>(
    _entities[0].properties[0],
  );

  /// See [FoodEntryEntity.foodItem].
  static final foodItem =
      obx.QueryRelationToOne<FoodEntryEntity, FoodItemEntity>(
        _entities[0].properties[1],
      );

  /// See [FoodEntryEntity.dateTime].
  static final dateTime = obx.QueryDateProperty<FoodEntryEntity>(
    _entities[0].properties[2],
  );

  /// See [FoodEntryEntity.quantity].
  static final quantity = obx.QueryDoubleProperty<FoodEntryEntity>(
    _entities[0].properties[3],
  );
}

/// [FoodItemEntity] entity fields to define ObjectBox queries.
class FoodItemEntity_ {
  /// See [FoodItemEntity.id].
  static final id = obx.QueryIntegerProperty<FoodItemEntity>(
    _entities[1].properties[0],
  );

  /// See [FoodItemEntity.barcode].
  static final barcode = obx.QueryStringProperty<FoodItemEntity>(
    _entities[1].properties[1],
  );

  /// See [FoodItemEntity.name].
  static final name = obx.QueryStringProperty<FoodItemEntity>(
    _entities[1].properties[2],
  );

  /// See [FoodItemEntity.brand].
  static final brand = obx.QueryStringProperty<FoodItemEntity>(
    _entities[1].properties[3],
  );

  /// See [FoodItemEntity.caloriesPer100g].
  static final caloriesPer100g = obx.QueryDoubleProperty<FoodItemEntity>(
    _entities[1].properties[4],
  );

  /// See [FoodItemEntity.carbsPer100g].
  static final carbsPer100g = obx.QueryDoubleProperty<FoodItemEntity>(
    _entities[1].properties[5],
  );

  /// See [FoodItemEntity.proteinPer100g].
  static final proteinPer100g = obx.QueryDoubleProperty<FoodItemEntity>(
    _entities[1].properties[6],
  );

  /// See [FoodItemEntity.fatsPer100g].
  static final fatsPer100g = obx.QueryDoubleProperty<FoodItemEntity>(
    _entities[1].properties[7],
  );

  /// See [FoodItemEntity.fiberPer100g].
  static final fiberPer100g = obx.QueryDoubleProperty<FoodItemEntity>(
    _entities[1].properties[8],
  );

  /// See [FoodItemEntity.servingSizeWeight].
  static final servingSizeWeight = obx.QueryDoubleProperty<FoodItemEntity>(
    _entities[1].properties[9],
  );

  /// See [FoodItemEntity.servingSizeName].
  static final servingSizeName = obx.QueryStringProperty<FoodItemEntity>(
    _entities[1].properties[10],
  );

  /// See [FoodItemEntity.allergies].
  static final allergies = obx.QueryStringVectorProperty<FoodItemEntity>(
    _entities[1].properties[11],
  );
}
